on: pull_request
name: CI Workflow - PR
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x 
      - run: npm ci
        name: install dependencies
      - run: npm run build
        name: run build script
      - run: npm test
        name: run tests